package com.theworkcode.report.pdf;

import java.io.ByteArrayOutputStream;
import java.time.format.DateTimeFormatter;
import java.util.Map;
import java.util.UUID;

import com.lowagie.text.Document;
import com.lowagie.text.Element;
import com.lowagie.text.Font;
import com.lowagie.text.FontFactory;
import com.lowagie.text.PageSize;
import com.lowagie.text.Paragraph;
import com.lowagie.text.Phrase;
import com.lowagie.text.pdf.PdfPCell;
import com.lowagie.text.pdf.PdfPTable;

import org.springframework.stereotype.Component;

/**
 * PDF report renderer using OpenPDF. Renders the verification result sheet
 * with The Work Code branding and the mandatory synthetic-data disclaimer.
 */
@Component
public class PdfReportGenerator {

    private static final Font BRAND = FontFactory.getFont(FontFactory.HELVETICA_BOLD, 18, new java.awt.Color(0, 74, 198));
    private static final Font H2 = FontFactory.getFont(FontFactory.HELVETICA_BOLD, 12, new java.awt.Color(11, 28, 48));
    private static final Font LABEL = FontFactory.getFont(FontFactory.HELVETICA, 8, new java.awt.Color(100, 116, 139));
    private static final Font VALUE = FontFactory.getFont(FontFactory.HELVETICA, 10, new java.awt.Color(11, 28, 48));
    private static final Font SMALL = FontFactory.getFont(FontFactory.HELVETICA, 7.5f, new java.awt.Color(100, 116, 139));

    public byte[] generate(Map<String, Object> report) {
        try (ByteArrayOutputStream out = new ByteArrayOutputStream()) {
            Document document = new Document(PageSize.A4, 40, 40, 40, 40);
            com.lowagie.text.pdf.PdfWriter.getInstance(document, out);
            document.open();

            // Header band
            Paragraph brand = new Paragraph("THE WORK CODE", BRAND);
            brand.add(new Phrase("   VERIFICATION REPORT", LABEL));
            document.add(brand);
            Paragraph subtitle = new Paragraph(
                    "Employment & Income Verification Infrastructure - DEMO / SYNTHETIC DATA", SMALL);
            subtitle.setSpacingAfter(12);
            document.add(subtitle);

            // Meta block
            PdfPTable meta = new PdfPTable(4);
            meta.setWidthPercentage(100);
            meta.setSpacingAfter(10);
            addMeta(meta, "Report ID", str(report, "reportCode"));
            addMeta(meta, "Generated At", str(report, "generatedAt"));
            addMeta(meta, "Generated By", str(report, "generatedBy", "platform"));
            addMeta(meta, "Audit Reference", str(report, "verificationId"));
            document.add(meta);

            // Subject block
            document.add(new Paragraph("Verification Subject", H2));
            PdfPTable subject = new PdfPTable(4);
            subject.setWidthPercentage(100);
            subject.setSpacingAfter(10);
            addMeta(subject, "Applicant", str(report, "applicantName"));
            addMeta(subject, "Employer", str(report, "employerName"));
            addMeta(subject, "Verification Type", str(report, "verificationType"));
            addMeta(subject, "Purpose", str(report, "purpose", "LOAN"));
            document.add(subject);

            // Result block
            document.add(new Paragraph("Verification Result", H2));
            PdfPTable result = new PdfPTable(3);
            result.setWidthPercentage(100);
            result.setSpacingAfter(10);
            addMeta(result, "Result", str(report, "result", "PENDING"));
            addMeta(result, "Confidence", report.get("confidence") == null ? "-"
                    : report.get("confidence") + "%");
            addMeta(result, "Verification Date",
                    DateTimeFormatter.ISO_OFFSET_DATE_TIME.format(java.time.OffsetDateTime.now()));
            document.add(result);

            // Verified attributes
            document.add(new Paragraph("Verified Attributes", H2));
            PdfPTable attrs = new PdfPTable(2);
            attrs.setWidthPercentage(100);
            attrs.setSpacingAfter(10);
            attrs.addCell(cell("Employment status verified against source records"));
            attrs.addCell(cell("Income components validated for internal consistency"));
            attrs.addCell(cell("Identity attributes matched (weighted scoring)"));
            attrs.addCell(cell("Payroll history reviewed for the selected lookback window"));
            document.add(attrs);

            // Risk indicators
            document.add(new Paragraph("Risk Indicators", H2));
            PdfPTable risk = new PdfPTable(3);
            risk.setWidthPercentage(100);
            risk.setSpacingAfter(10);
            addMeta(risk, "Risk Score", str(report, "riskScore", "12"));
            addMeta(risk, "Risk Band", str(report, "riskBand", "LOW"));
            addMeta(risk, "Data Freshness", "Synthetic employer payroll feed - updated every pay period");
            document.add(risk);

            // Authorization statement
            document.add(new Paragraph("Authorization Statement", H2));
            Paragraph auth = new Paragraph(
                    "This verification was generated for the permissible purpose recorded on the request. "
                    + "The subject's authorization is retained with the verification record and is available "
                    + "for audit review. Demo environment: production deployments require applicable legal, "
                    + "consent, and compliance controls.",
                    VALUE);
            auth.setSpacingAfter(10);
            document.add(auth);

            // Disclaimer footer
            Paragraph disclaimer = new Paragraph(
                    "DISCLAIMER: This report was generated by The Work Code demo platform using synthetic "
                    + "demonstration data only. It does not connect to any real workforce verification network, "
                    + "is not affiliated with any commercial verification bureau, and must not be used for "
                    + "real underwriting decisions.",
                    SMALL);
            disclaimer.setSpacingBefore(16);
            document.add(disclaimer);
            Paragraph auditLine = new Paragraph(
                    "Audit trail reference: " + str(report, "verificationId", "-")
                    + " | Report UUID: " + UUID.randomUUID(), SMALL);
            document.add(auditLine);

            document.close();
            return out.toByteArray();
        } catch (Exception e) {
            throw new IllegalStateException("Report generation failed: " + e.getMessage(), e);
        }
    }

    private void addMeta(PdfPTable table, String label, String value) {
        PdfPCell labelCell = new PdfPCell(new Phrase(label.toUpperCase(), LABEL));
        labelCell.setBorder(com.lowagie.text.Rectangle.NO_BORDER);
        PdfPCell valueCell = new PdfPCell(new Phrase(value, VALUE));
        valueCell.setBorder(com.lowagie.text.Rectangle.NO_BORDER);
        table.addCell(labelCell);
        table.addCell(valueCell);
    }

    private PdfPCell cell(String text) {
        PdfPCell c = new PdfPCell(new Phrase(text, VALUE));
        c.setHorizontalAlignment(Element.ALIGN_LEFT);
        c.setPadding(6);
        c.setBorderColor(new java.awt.Color(226, 232, 240));
        return c;
    }

    private String str(Map<String, Object> map, String key) {
        return str(map, key, "-");
    }

    private String str(Map<String, Object> map, String key, String def) {
        Object v = map.get(key);
        return v == null || String.valueOf(v).isBlank() ? def : String.valueOf(v);
    }
}
